import time
import asyncio
from fastapi import APIRouter, Depends, Request
from models.schemas import GenerateRequest, ReplyRequest, OnboardRequest, FeedbackRequest
from utils.security import get_current_user
from utils.responses import success_response, error_response
from utils.cache import cache
from services.db_service import get_user_data, save_user_post, get_user_history, update_user_profile, mark_onboarded, save_feedback
from ai_tech_creator.post_generator import generate_post

router = APIRouter(tags=["posts"])

def _generate_logic(user_id, category=None, series_topic=None):
    user_data = get_user_data(user_id)
    if not user_data:
        raise Exception("User not found")
        
    profile = {
        "niche": user_data['niche'],
        "experience": user_data['experience'],
        "tone": user_data['tone']
    }
    
    topic = series_topic or "AI trends in software engineering"
    cat = category or "Career growth"
    prompt = f"Topic: {topic}\nCategory: {cat}\nNiche: {profile['niche']}\nTone: {profile['tone']}\nWrite a viral LinkedIn post."
    post_text = generate_post(prompt)
    
    if isinstance(post_text, dict) and not post_text.get("success"):
        raise Exception(post_text.get("error", "Rate limit error"))
        
    post_data = {
        "post": post_text,
        "rationale": "Generated by AI",
        "status": "LLM",
        "category": cat,
        "topic": topic,
        "engagement_score": "High",
        "engagement_reason": "Strong hook",
        "timestamp": time.time(),
        "post_state": "GENERATED",
        "scheduled_time": None
    }
    
    post_data['id'] = save_user_post(user_id, post_data)
    return post_data

@router.get("/user_data")
@cache(ttl=60)
# To enable auth again: add Depends(get_current_user)
async def api_user_data(request: Request, current_user: int = 1):
    print("API HIT:", request.url.path)
    data = get_user_data(current_user)
    if not data:
        return error_response("User not found", 404)
    return success_response(data)

@router.get("/history")
@cache(ttl=30)
# To enable auth again: add Depends(get_current_user)
async def history(request: Request, current_user: int = 1):
    print("API HIT:", request.url.path)
    history_data = get_user_history(current_user)
    for item in history_data:
        if 'post_text' in item:
            item['post'] = item.pop('post_text')
    return success_response({"history": history_data})

@router.post("/onboard")
# To enable auth again: add Depends(get_current_user)
async def onboard_user(req: OnboardRequest, request: Request, current_user: int = 1):
    print("API HIT:", request.url.path)
    update_user_profile(current_user, req.niche, 'Engineer', 'Professional', req.goal)
    mark_onboarded(current_user)
    return success_response(message="Onboarded successfully")

@router.post("/generate-post")
# To enable auth again: add Depends(get_current_user)
async def generate(req: GenerateRequest, request: Request, current_user: int = 1):
    print("API HIT:", request.url.path)
    print("REQUEST TIME:", time.time())
    print("=== GENERATE API HIT ===")
    print("Request:", req)
    try:
        print("Calling AI service...")
        post_data = await asyncio.wait_for(
            asyncio.to_thread(_generate_logic, current_user, req.category, req.series_topic),
            timeout=8.0
        )
        print("AI Response:", post_data)
        return success_response(post_data)
    except asyncio.TimeoutError:
        print("ERROR: AI Generation timed out.")
        return error_response("AI Generation timed out after 8 seconds.", 408)
    except Exception as e:
        import traceback
        print("ERROR:", str(e))
        traceback.print_exc()
        raise e

@router.post("/reply")
# To enable auth again: add Depends(get_current_user)
async def api_reply(req: ReplyRequest, request: Request, current_user: int = 1):
    print("API HIT:", request.url.path)
    prompt = f"Write a short, engaging reply to this LinkedIn comment: {req.comment}"
    try:
        reply = await asyncio.wait_for(
            asyncio.to_thread(generate_post, prompt),
            timeout=8.0
        )
        return success_response({"reply": reply})
    except asyncio.TimeoutError:
        print("ERROR: AI Reply Generation timed out.")
        return error_response("AI Generation timed out after 8 seconds.", 408)
    except Exception as e:
        import traceback
        print("ERROR:", str(e))
        traceback.print_exc()
        raise e

@router.post("/feedback")
# To enable auth again: add Depends(get_current_user)
async def api_feedback(req: FeedbackRequest, request: Request, current_user: int = 1):
    print("API HIT:", request.url.path)
    save_feedback(current_user, req.post_id, 1 if req.is_useful else 0, req.comments)
    return success_response(message="Feedback saved")
